- name: Create users, set passwords, and add SSH keys
  hosts: [test]
  become: yes
  vars:
    users:
      - name: admin.jdang
        ssh_key: "keys/admin.jdang.pub"
        password_file: "keys/admin.jdang.key"
      - name: admin.snasir
        ssh_key: "keys/admin.snasir.pub"
        password_file: "keys/admin.snasir.key"
      - name: admin.rmendez
        ssh_key: "keys/admin.rmendez.pub"
        password_file: "keys/admin.rmendez.key"

  tasks:
    - name: Ensure the group "OCCU-ADMINS" exists
      group:
        name: OCCU-ADMINS
        state: present

    - name: Read hashed passwords from files
      command: cat "{{ item.password_file }}"
      register: user_passwords
      changed_when: false
      loop: "{{ users }}"

    - name: Create users and add them to "OCCU-ADMINS" group
      user:
        name: "{{ item.item.name }}"
        groups: OCCU-ADMINS
        append: yes
        shell: /bin/bash
        create_home: yes
        state: present
        password: "{{ item.stdout | trim }}"
      loop: "{{ user_passwords.results }}"


    - name: Set up SSH directory for each user
      file:
        path: "/home/{{ item.name }}/.ssh"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0700'
      loop: "{{ users }}"

    - name: Add public keys to authorized_keys
      copy:
        src: "{{ item.ssh_key }}"
        dest: "/home/{{ item.name }}/.ssh/authorized_keys"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0600'
      loop: "{{ users }}"

